version: 2.1
orbs:
  docker: circleci/docker@1.5.0
jobs:
  build_and_push:
    executor: docker/docker
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Build and push Docker image"
          command: |
            if [ "$CIRCLE_BRANCH" == "noble" ]; then
              docker build -t qrledger/qrl-docker-ci:noble .
              docker tag qrledger/qrl-docker-ci:noble qrledger/qrl-docker-ci:latest
              echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
              docker push qrledger/qrl-docker-ci:noble
              docker push qrledger/qrl-docker-ci:latest
            else
              docker build -t qrledger/qrl-docker-ci:$CIRCLE_BRANCH .
              echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
              docker push qrledger/qrl-docker-ci:$CIRCLE_BRANCH
            fi
workflows:
  version: 2
  commit:
    jobs:
      - build_and_push:
          filters:
            branches:
              ignore:
                - gh-pages
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
                - noble
                - xenial
                - bionic
    jobs:
      - build_and_push